package constants

const (

	// 1xx informational response
	ERROR_CODE_CONTINUE            = 100
	ERROR_CODE_SWITCHING_PROTOCOLS = 101
	ERROR_CODE_PROCESSING          = 102
	ERROR_CODE_EARLY_HINTS         = 103

	// 2xx success
	ERROR_CODE_OK                            = 200
	ERROR_CODE_CREATED                       = 201
	ERROR_CODE_ACCEPTED                      = 202
	ERROR_CODE_NON_AUTHORITATIVE_INFORMATION = 203
	ERROR_CODE_NO_CONTENT                    = 204
	ERROR_CODE_RESET_CONTENT                 = 205
	ERROR_CODE_PARTIAL_CONTENT               = 206

	// 3xx redirection
	ERROR_CODE_MULTIPLE_CHOICES   = 300
	ERROR_CODE_MOVED_PERMANENTLY  = 301
	ERROR_CODE_FOUND              = 302
	ERROR_CODE_SEE_OTHER          = 303
	ERROR_CODE_NOT_MODIFIED       = 304
	ERROR_CODE_TEMPORARY_REDIRECT = 307
	ERROR_CODE_PERMANENT_REDIRECT = 308

	// 4xx client errors
	ERROR_CODE_BAD_REQUEST                     = 400
	ERROR_CODE_UNAUTHORIZED                    = 401
	ERROR_CODE_PAYMENT_REQUIRED                = 402
	ERROR_CODE_FORBIDDEN                       = 403
	ERROR_CODE_NOT_FOUND                       = 404
	ERROR_CODE_METHOD_NOT_ALLOWED              = 405
	ERROR_CODE_NOT_ACCEPTABLE                  = 406
	ERROR_CODE_PROXY_AUTHENTICATION_REQUIRED   = 407
	ERROR_CODE_REQUEST_TIMEOUT                 = 408
	ERROR_CODE_CONFLICT                        = 409
	ERROR_CODE_GONE                            = 410
	ERROR_CODE_LENGTH_REQUIRED                 = 411
	ERROR_CODE_PRECONDITION_FAILED             = 412
	ERROR_CODE_PAYLOAD_TOO_LARGE               = 413
	ERROR_CODE_URI_TOO_LONG                    = 414
	ERROR_CODE_UNSUPPORTED_MEDIA_TYPE          = 415
	ERROR_CODE_RANGE_NOT_SATISFIABLE           = 416
	ERROR_CODE_EXPECTATION_FAILED              = 417
	ERROR_CODE_IM_A_TEAPOT                     = 418
	ERROR_CODE_UNPROCESSABLE_ENTITY            = 422
	ERROR_CODE_TOO_EARLY                       = 425
	ERROR_CODE_UPGRADE_REQUIRED                = 426
	ERROR_CODE_PRECONDITION_REQUIRED           = 428
	ERROR_CODE_TOO_MANY_REQUESTS               = 429
	ERROR_CODE_REQUEST_HEADER_FIELDS_TOO_LARGE = 431
	ERROR_CODE_UNAVAILABLE_FOR_LEGAL_REASONS   = 451

	// 5xx server errors
	ERROR_CODE_INTERNAL_SERVER_ERROR           = 500
	ERROR_CODE_NOT_IMPLEMENTED                 = 501
	ERROR_CODE_BAD_GATEWAY                     = 502
	ERROR_CODE_SERVICE_UNAVAILABLE             = 503
	ERROR_CODE_GATEWAY_TIMEOUT                 = 504
	ERROR_CODE_HTTP_VERSION_NOT_SUPPORTED      = 505
	ERROR_CODE_VARIANT_ALSO_NEGOTIATES         = 506
	ERROR_CODE_INSUFFICIENT_STORAGE            = 507
	ERROR_CODE_LOOP_DETECTED                   = 508
	ERROR_CODE_NOT_EXTENDED                    = 510
	ERROR_CODE_NETWORK_AUTHENTICATION_REQUIRED = 511
)
