package constants

const (
	HTTP_METHOD_GET     = "GET"
	HTTP_METHOD_HEAD    = "HEAD"
	HTTP_METHOD_POST    = "POST"
	HTTP_METHOD_PUT     = "PUT"
	HTTP_METHOD_DELETE  = "DELETE"
	HTTP_METHOD_CONNECT = "CONNECT"
	HTTP_METHOD_OPTIONS = "OPTIONS"
	HTTP_METHOD_TRACE   = "TRACE"
	HTTP_METHOD_PATCH   = "PATCH"
)
